__author__ = 'Dani'


class KeyDicts(object):

    #INDICATOR KEYS
    TOTAL_DEALS = 0
    AGRICULTURE_DEALS = 1
    CONSERVATION_DEALS = 2
    FORESTRY_DEALS = 3
    INDUSTRY_DEALS = 4
    RENEWABLE_ENERGY_DEALS = 5
    TOURISM_DEALS = 6
    OTHER_DEALS = 7
    UNKNOWN_DEALS = 8

    INTENDED_DEALS = 9
    CONCLUDED_DEALS = 10
    FAILED_DEALS = 11

    HECTARES_TOTAL_DEALS = 12
    HECTARES_INTENDED_DEALS = 13
    HECTARES_CONTRACT_DEALS = 14
    HECTARES_PRODUCTION_DEALS = 15

    BIOFUELS_DEALS = 16
    FOOD_CROPS_DEALS = 17
    LIVESTOCK_DEALS = 18
    NON_FOOD_AGRICULTURAL_COMMODITIES_DEALS = 19
    AGRIUNSPECIFIED_DEALS = 20

    FOR_WOOD_AND_FIBRE_DEALS = 21
    FOR_CARBON_SEQUESTRATION_REDD_DEALS = 22
    FORESTUNSPECIFIED_DEALS = 23

    HECTARES_AGRICULTURE_DEALS = 24

