__author__ = 'Dani'


class KeyDicts(object):

    #INDICATOR KEYS
    TOTAL_DEALS = 0
    AGRICULTURE_DEALS = 1
    CONSERVATION_DEALS = 2
    FORESTRY_DEALS = 3
    INDUSTRY_DEALS = 4
    RENEWABLE_ENERGY_DEALS = 5
    TOURISM_DEALS = 6
    OTHER_DEALS = 7
    UNKNOWN_DEALS = 8

    INTENDED_DEALS = 9
    CONCLUDED_DEALS = 10
    FAILED_DEALS = 11

    HECTARES_TOTAL_DEALS = 12
    HECTARES_INTENDED_DEALS = 13
    HECTARES_CONTRACT_DEALS = 14
    HECTARES_PRODUCTION_DEALS = 15

    BIOFUELS_DEALS = 16
