__author__ = 'Dani'


class KeyDicts(object):

    #INDICATOR KEYS
    TOTAL_DEALS = "N1"
    HECTARES_TOTAL_DEALS = "HA1"

    CONCLUDED_DEALS = "N2"
    HECTARES_CONTRACT_DEALS = "HA2"

    INTENDED_DEALS = "N3"
    HECTARES_INTENDED_DEALS = "HA3"

    FAILED_DEALS = "N4"
    HECTARES_FAILED_DEALS = "HA4"

    IN_PRODUCTION_DEALS = "N5"
    HECTARES_PRODUCTION_DEALS = "HA5"

    AGRICULTURE_DEALS = "N6"
    CONSERVATION_DEALS = "N7"
    FORESTRY_DEALS = "N8"
    INDUSTRY_DEALS = "N9"
    RENEWABLE_ENERGY_DEALS = "N10"
    TOURISM_DEALS = "N11"
    OTHER_DEALS = "N12"
    UNKNOWN_DEALS = "N13"
    MINING_DEALS = "N23"
    LANDSPECULATION_DEALS = "N24"
    OIL_GAS_DEALS = "N25"


    BIOFUELS_DEALS = "N14"
    FOOD_CROPS_DEALS = "N15"
    LIVESTOCK_DEALS = "N16"
    NON_FOOD_AGRICULTURAL_COMMODITIES_DEALS = "N17"
    AGRIUNSPECIFIED_DEALS = "N18"
    FOODER_DEALS = "N22"

    FOR_WOOD_AND_FIBRE_DEALS = "N19"
    FOR_CARBON_SEQUESTRATION_REDD_DEALS = "N20"
    FORESTUNSPECIFIED_DEALS = "N21"

    HECTARES_AGRICULTURE_DEALS = "HA6"
    HECTARES_CONSERVATION_DEALS = "HA7"
    HECTARES_FORESTRY_DEALS = "HA8"
    HECTARES_INDUSTRY_DEALS = "HA9"
    HECTARES_RENEWABLE_ENERGY_DEALS = "HA10"
    HECTARES_TOURISM_DEALS = "HA11"
    HECTARES_OTHER_DEALS = "HA12"
    HECTARES_UNKNOWN_DEALS = "HA13"
    HECTARES_MINING_DEALS = "HA23"
    HECTARES_LANDSPECULATION_DEALS = "HA24"
    HECTARES_OIL_GAS_DEALS = "HA25"



    HECTARES_BIOFUELS_DEALS = "HA14"
    HECTARES_FOOD_CROPS_DEALS = "HA15"
    HECTARES_LIVESTOCK_DEALS = "HA16"
    HECTARES_NON_FOOD_AGRICULTURAL_COMMODITIES_DEALS = "HA17"
    HECTARES_AGRIUNSPECIFIED_DEALS = "HA18"
    HECTARES_FOODER_DEALS = "HA22"

    HECTARES_FOR_WOOD_AND_FIBRE_DEALS = "HA19"
    HECTARES_FOR_CARBON_SEQUESTRATION_REDD_DEALS = "HA20"
    HECTARES_FORESTUNSPECIFIED_DEALS = "HA21"

